{% set name = "robocorp-excel" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp_excel-{{ version }}.tar.gz
  sha256: 833183ef0372ebeb7df515f97d1840a4e8b8784f64391aa19e0e4ea1ef457100

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pillow >=9.1.1,<=11.0.0
    - xlrd >=2.0.1,<3.0.0
    - xlwt >=1.3.0,<2.0.0
    - xlutils >=2.0.0,<3.0.0
    - openpyxl >=3.0.9,<4.0.0
    - typing-extensions >=4.5.0,<5.0.0

test:
  imports:
    - robocorp.excel
  commands:
    #- pip check
  requires:
    - pip

about:
  summary: Robocorp Excel automation library
  home: https://github.com/robocorp/robo/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
